Output ./demo.gif

Require rainfrog

Set Shell zsh
Set Theme "tokyonight-storm"
Set Width 1800
Set Height 1000
Set Padding 20

# https://www.nerdfonts.com/font-downloads
Set FontFamily "GohuFont uni14 Nerd Font Mono"
Set PlaybackSpeed 0.75
Set TypingSpeed 250ms

Show
Sleep 250ms
Type "rainfrog"
Sleep 1s
Hide
Backspace 8
Sleep 1.5s
Type "make dev"
Enter
Sleep 15s
Show
Sleep 3s
Enter
Sleep 500ms
Type "jjj"
Sleep 500ms
Type "/github"
Sleep 500ms
Enter
Sleep 250ms
Escape
Sleep 500ms
Escape
Type "h"
Sleep 500ms
Type "j"
Sleep 500ms
Enter
Sleep 250ms
Type "jjj"
Sleep 250ms
Enter
Sleep 500ms
Ctrl+H
Sleep 1s
Type "v"
Sleep 1s
Type "j"
Sleep 1s
Type "e"
Sleep 500ms
Type "y"
Sleep 1s
Ctrl+J
Sleep 500ms
Type "dd"
Sleep 500ms
Type "i"
Sleep 250ms
Type@150ms "select * from public.user where email ilike '%atreides%'"
Sleep 250ms
Alt+Enter
Sleep 2s
Type "0eeli"
Backspace 9
Type "delete"
Sleep 500ms
Alt+Enter
Sleep 1s
Type "N"
Sleep 500ms
Ctrl+G
Sleep 1s
Type "jjj"
Sleep 500ms
Type "y"
Sleep 750ms
Type "I"
Sleep 1s
Alt+Enter
Sleep 5s
